### ISSUE TITLE
Show we have a list of "guides" inside Livebook itself

### ISSUE THREAD

**Issue by hugobarauna** [livebook-dev/livebook.dev#101]
I have seen people trying to find docs/guides about Livebook multiple times without knowing there's a Learn section inside Livebook that could answer some of their questions.

Although we plan to expand our docs at https://hexdocs.pm/livebook, in the meantime, maybe we can just add another entry to the main menu with a "Guides" title, something like that:

![CleanShot 2024-06-27 at 10 49 00](https://github.com/livebook-dev/livebook.dev/assets/2719/47394962-5a8e-488c-b8ae-279560c7474a)

In that section, we could explain multiple guides inside the Livebook itself.

This would help people who go to the Livebook website looking for docs.

**Comment by josevalim** [comment]
Suggestion: make "Guides" link to "hexdocs.pm/livebook" and we change the README to mention the Learn section as early as possible?

**Comment by hugobarauna** [comment]
@josevalim Good idea. 👍
