### ISSUE TITLE
Add a link to the Livebook repo

### ISSUE THREAD

**Issue by ream88** [livebook-dev/livebook.dev#33]
I'm always searching on the website for a link to the GitHub repo of Livebook itself, but the only one linked is the website. Should I add another GitHub icon? Maybe in the header?

**Comment by jonatanklosko** [comment]
Hey @ream88!

![image](https://user-images.githubusercontent.com/17034772/169026285-a0396b51-ea9c-4956-be2e-caae8228f173.png)

The right button takes you to the repo, we changed the wording to "Join the community", but I think "Visit our GitHub" and the icon should be good enough pointers. Does that work for you?

**Comment by ream88** [comment]
Lol, sorry. Completely missed that somehow. I even searched through the HTML source code, but did not catch that. Well, ignore this then 😉

**Comment by jonatanklosko** [comment]
Great, no worries :)
