### ISSUE TITLE
Most recent windows installer fails to run after install

### ISSUE THREAD

**Issue by bjconlan** [livebook-dev/livebook.dev#51]
OS: Windows 10. 64 bit
Installer filename: LivebookInstall-latest-windows-x86_64.exe (downloaded 4-11-2022)
Shortcut Execution Target:  C:\Users\bjcon\AppData\Local\Livebook\LivebookLauncher.exe

After installing the installer and executing the shortcut added to the desktop I receive the following error:
![image](https://user-images.githubusercontent.com/394160/199920700-72c512ee-0ab5-44d7-a8ce-e301ca91f2e1.png)

**Comment by josevalim** [comment]
Thank you for the report. This is fixed on main and available in nightly releases: https://github.com/livebook-dev/livebook#desktop-app
