### ISSUE TITLE
 Windows Defender reporting for Trojan:Win32/Wacatac.D!ml  during Livebook install

### ISSUE THREAD

**Issue by Sereton** [livebook-dev/livebook.dev#56]
I downloaded  Livebook from here: https://livebook.dev/releases/latest/LivebookInstall-latest-windows-x86_64.exe

Windows 11 is reporting the Trojan mentioned in the title. Is this a false positive? I tried to find more info to no avail.

![Screenshot 2022-12-31 192603](https://user-images.githubusercontent.com/5839948/210158772-50d8631d-e9ab-47d8-a3c1-c0b7eca913ae.png)

**Comment by josevalim** [comment]
Yes, it is a false positive. We are working on tackling this. You should find existing issues in the Livebook-dev/Livebook repo. Thanks for the report and happy new year!

**Comment by Sereton** [comment]
Obrigado Jose, Feliz ano novo!
