### ISSUE TITLE
Feedback on contents from integrations

### ISSUE THREAD

**Issue by josevalim** [livebook-dev/livebook.dev#58]
## Elixir

* [ ] In "Connecting to a running Elixir", let's add a link to https://fly.io/docs/elixir/advanced-guides/connect-livebook-to-your-app/
* [ ] Let's add a subsection about nerves_livebook
* [ ] Let's mention it [Runs within your with Mix projects](https://github.com/livebook-dev/livebook/blob/main/lib/livebook/notebook/learn/elixir_and_livebook.livemd#mix-projects) - it will probably need an accompanying article/video

## HF

* [ ] Update the list of models
* [ ] Let's link to the Bumblebee announcement video at the top
* [ ] In "Use the generated code inside your app", let's link to the second part of the video

## SQL

* [ ] Let's mention the supported databases (perhaps link back to the integrations page)

## Databases

* [ ] All of them should mention that then you can write queries directly from Livebook too
* [ ] For the ones that have videos, let's link to them

## VegaLite and MapLibre

* [ ] Compress images: some are almost 1MB
* [ ] We can list some of the features from the smart cell. For example, under VegaLite, we could say:

  "Livebook's Chart Smart cell lets you build charts using a simple UI. You can plot points, pie, add binning, coloring, yada, yada, and much more with few clicks."

  And then, the next section - "All the power from Vega-Lite" - can say: "When the Smart cell is not enough, Livebook offers a tiny API layer that gives you full access to all of VegaLite features and makes it easier to build all sorts of Vega-Lite charts."

**Comment by hugobarauna** [comment]
I'm on it.
