### ISSUE TITLE
News section overflows sponsors section on Safari

### ISSUE THREAD

**Issue by nandofarias** [livebook-dev/livebook.dev#7]
Good day folks, fantastic work. Congrats to the whole team.

As a user of Safari, I noticed a small overflow on the news section over the fly.io logo.

Here is how it looks to me:
![Screen Shot 2021-10-19 at 12 08 51](https://user-images.githubusercontent.com/1944560/137939379-049a2d18-5fd6-4ff3-837c-c8d9634c7c08.png)

This is probably related to Safari interpretation of content height (https://stackoverflow.com/a/44773109/4660005)

Changing the CSS class on https://github.com/livebook-dev/livebook_website/blob/main/src/index.html#L372 from `h-full` to `h-auto` should get the job done without any changes on the behavior for other browsers.

Thanks again for the fantastic website.

**Comment by jonatanklosko** [comment]
Hey, @nandofarias, thanks for all the details! Looking closer I think the `h-full` class was just a leftover from me trying something and we shouldn't need it in the first place. I've just removed it in f54b8a6ed18e239147ee270784436d563ef922d1, please let me know if the website looks good for you now :D
