### ISSUE TITLE
cannot type # in code or markdown block

### ISSUE THREAD

**Issue by woylie** [livebook-dev/livebook.dev#76]
I cannot type a `#` symbol in a code or markdown block. Nothing happens. I didn't find any shortcuts blocking the key combination. On my keyboard layout (Neo 2), the `#` symbol is mapped to `right option + z`. Interestingly, it works fine in a section header.

macOS 13.4.1
Chrome 114.0.5735.198 (Official Build) (arm64)
livebook 0.9.3

**Comment by woylie** [comment]
I saw now that this key combination toggles the word wrap in the cell.

**Comment by josevalim** [comment]
Hi @woylie! Yes, this is a monaco+vscode shortcut. You would need to use a different mapping. :)

**Comment by woylie** [comment]
> Hi @woylie! Yes, this is a monaco+vscode shortcut. You would need to use a different mapping. :)

I'm sorry, how? I don't see any settings to change the shortcuts in LiveView.

**Comment by josevalim** [comment]
That's the thing, we do not have ways to change it. It comes from the Monaco editor that we use (and VS Code uses the same shortcut too).

**Comment by woylie** [comment]
That's very disappointing. Big thumbs down for Monaco and VS Code from me. The option/alt key is meant for additional characters, not shortcuts, after all.
