### ISSUE TITLE
Connect local node to elixir node in docker through ssh tunnel

### ISSUE THREAD

**Issue by mrdotb** [livebook-dev/livebook.dev#84]
Hello

I spend some time yesterday to connect livebook to a node running inside a docker in a vps on hetzner through ssh tunnel

It was not that simple but I finally succeed.

# create a network interface on computer
```bash
local>
sudo ip addr add 127.0.0.2/8 dev lo
```

Edit /etc/ssh/sshd_config check if the values are like below
```bash
server>
vi /etc/ssh/sshd_config
GatewayPorts yes
AllowTcpForwarding yes
```

Restart ssh server
```bash
server>
systemctl restart ssh
```

Add this env to the server node note the ip after nameofnode must be the same as the network we created on our local network
```bash
RELEASE_DISTRIBUTION="name"
RELEASE_COOKIE="cookie"
RELEASE_NODE="nameofnode@127.0.0.2"
BEAM_PORT="19000"
```

Add this script to /rel/env.sh.eex we want inet_dist_listen to be on port 19000 only
```
local>
#!/bin/sh

case $RELEASE_COMMAND in
  start*|daemon*)
    ELIXIR_ERL_OPTIONS="-kernel inet_dist_listen_min $BEAM_PORT inet_dist_listen_max $BEAM_PORT"
    export ELIXIR_ERL_OPTIONS
    ;;
  *)
    ;;
esac
```

Build and deploy the docker

```bash
server>
docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
> 172.17.0.4
```

Tunnel the container port 4369 (epmd) and port 19000 (distributed erlang communications) to the local network we created earlier
```bash
ssh -L 127.0.0.2:4369:172.17.0.4:4369 -L 127.0.0.2:19000:172.17.0.4:19000 root@ipofyourserver -N
```

Run livebook
```
LIVEBOOK_DISTRIBUTION=name LIVEBOOK_NODE=lb@127.0.0.2 LIVEBOOK_DEFAULT_RUNTIME=attached:nameofnode@127.0.0.2:cookie livebook server
```

Hello,

I spent some time yesterday setting up a connection between Livebook and a node running inside a Docker container on a VPS from Hetzner, using an SSH tunnel. Although it was challenging, I was eventually successful. Here's how I did it:

1. **Create a Network Interface on Your Local Machine**

    ```
    sudo ip addr add 127.0.0.2/8 dev lo
    ```

2. **Modify SSH Configuration on Your Server**

    Open `/etc/ssh/sshd_config` and ensure the following values are set:

    ```
    GatewayPorts yes
    AllowTcpForwarding yes
    ```

    Restart the SSH server afterwards:

    ```
    systemctl restart ssh
    ```

3. **Set Up Environment Variables on Your Server**

    Note that the IP address following the node name must match the network we created on our local machine:

    ```
    RELEASE_DISTRIBUTION="name"
    RELEASE_COOKIE="cookie"
    RELEASE_NODE="nameofnode@127.0.0.2"
    BEAM_PORT="19000"
    ```

4. **Modify /rel/env.sh.eex**

    Add the following script to `/rel/env.sh.eex`. This configures `inet_dist_listen` to only use port 19000:

    ```
    #!/bin/sh

    case $RELEASE_COMMAND in
      start*|daemon*)
        ELIXIR_ERL_OPTIONS="-kernel inet_dist_listen_min $BEAM_PORT inet_dist_listen_max $BEAM_PORT"
        export ELIXIR_ERL_OPTIONS
        ;;
      *)
        ;;
    esac
    ```

5. **Build and Deploy the Docker Container**

6. **Get container IP**

    ```
    docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
    > 172.17.0.4
    ```

6. **Create an SSH Tunnel**

    Tunnel the container's ports 4369 (epmd) and 19000 (distributed Erlang communications) to the local network we created earlier:

    ```
    ssh -L 127.0.0.2:4369:172.17.0.4:4369 -L 127.0.0.2:19000:172.17.0.4:19000 root@ipofyourserver -N
    ```

7. **Run Livebook**

    ```
    LIVEBOOK_DISTRIBUTION=name \
    LIVEBOOK_NODE=lb@127.0.0.2 \
    LIVEBOOK_DEFAULT_RUNTIME=attached:nameofnode@127.0.0.2:cookie \
    livebook server
    ```

I believe there might be a better solution to establish this connection. I'd like to open this topic for discussion and appreciate any suggestions for improvement.

Hello,

I spent some time today setting up a connection between Livebook and a node running inside a Docker container on a VPS from Hetzner, using an SSH tunnel. Although it was challenging, I was eventually successful. Here's how I did it:

1. **Create a Network Interface on Your Local Machine**

    ```bash
    local> sudo ip addr add 127.0.0.2/8 dev lo
    ```

2. **Modify SSH Configuration on Your Server**

    Open `/etc/ssh/sshd_config` and ensure the following values are set:

    ```bash
    server> vi /etc/ssh/sshd_config
    GatewayPorts yes
    AllowTcpForwarding yes
    ```

    Restart the SSH server afterwards:

    ```bash
    server> systemctl restart ssh
    ```

3. **Set Up Environment Variables on the docker**

    Note that the IP address following the node name must match the network we created on our local machine:

    ```bash
    RELEASE_DISTRIBUTION="name"
    RELEASE_COOKIE="cookie"
    RELEASE_NODE="nameofnode@127.0.0.2"
    BEAM_PORT="19000"
    ```

4. **Add /rel/env.sh.eex to your project**

    Add the following script to `/rel/env.sh.eex`. This configures `inet_dist_listen` to only use port 19000:

    ```bash
    #!/bin/sh

    case $RELEASE_COMMAND in
      start*|daemon*)
        ELIXIR_ERL_OPTIONS="-kernel inet_dist_listen_min $BEAM_PORT inet_dist_listen_max $BEAM_PORT"
        export ELIXIR_ERL_OPTIONS
        ;;
      *)
        ;;
    esac
    ```

5. **Build and Deploy the Docker Container on Your Server**

6. **Get the ip of the container running the node on Your Server**

    ```bash
    server> docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
    > 172.17.0.4
    ```

6. **Create an SSH Tunnel on Your Local Machine**

    Tunnel the container's ports 4369 (epmd) and 19000 (distributed Erlang communications) to the local network we created earlier:

    ```bash
    local> ssh -L 127.0.0.2:4369:172.17.0.4:4369 -L 127.0.0.2:19000:172.17.0.4:19000 root@ipofyourserver -N
    ```

7. **Run Livebook on Your Local Machine**

    ```bash
    local> LIVEBOOK_DISTRIBUTION=name LIVEBOOK_NODE=lb@127.0.0.2 LIVEBOOK_DEFAULT_RUNTIME=attached:nameofnode@127.0.0.2:cookie livebook server
    ```

And it's work !

Still I believe there may be a simpler solution than this. Maybe adding a vpn like zerotier or tailscale to my docker image directly.
I will be happy to explore more and contribute to the documentation to cover this part.

**Comment by jonatanklosko** [comment]
Hey @mrdotb, thanks for sharing :) Connecting to a remote node is quite specific to the deployment environment, so we don't have a single guide on that. When connecting local Livebook you need some kind of tunneling or VPN, [another example](https://elixirforum.com/t/tiny-helper-script-to-start-livebook-connected-to-production-fly-io-or-development/51183). We may document various approaches once we have additional documentation around Livebook features. You can also consider posting to Elixir forum.

(Nitpick: it looks like your comment has duplicated steps :))
